import Head from 'next/head'

export default function Page() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
            <h1>
                Extended Format Service API
            </h1>
            <p>
                Send your rawtx to the /api endpoint to get the extended format in the response.
            </p>
            </main>
        </div>
    )
}